
server:
  port: 8191
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  datasource:
    url: jdbc:mysql://localhost/sample2?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
       
jpa:
  hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 